# Generated by Django 3.2.5 on 2021-07-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='animal_image',
            field=models.CharField(default='animal.jpg', max_length=300),
            preserve_default=False,
        ),
    ]
