# Generated by Django 3.2.5 on 2021-07-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
        ('animals', '0002_animal_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='schedule',
            field=models.ManyToManyField(related_name='animals', to='schedules.Schedule'),
        ),
    ]
