# Generated by Django 3.2.5 on 2021-07-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='message',
            field=models.TextField(default='Please can I cuddle Jeremy', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='request_status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
